# Generated by Django 2.2.4 on 2022-01-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_question_testcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='input_line',
        ),
    ]
