# Generated by Django 2.2.4 on 2022-01-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_testcase_input_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='input_line',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='output',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
