# Generated by Django 2.2.4 on 2022-01-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_testcase_input_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='id',
        ),
        migrations.AddField(
            model_name='testcase',
            name='tc_id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
