# Generated by Django 2.2.4 on 2022-01-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20220117_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='input_type',
        ),
        migrations.AddField(
            model_name='question',
            name='input_type',
            field=models.CharField(blank=True, choices=[('int', 'INT'), ('char', 'CHAR')], max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='output_type',
            field=models.CharField(blank=True, choices=[('int', 'INT'), ('char', 'CHAR')], max_length=10),
        ),
        migrations.AddField(
            model_name='testcase',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
