# Generated by Django 2.2.4 on 2022-01-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20220117_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='solved_questions',
            field=models.ManyToManyField(blank=True, null=True, related_name='solved_by', to='backend.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')]),
        ),
    ]
