# Generated by Django 2.2.4 on 2022-01-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20220118_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[('Easy', 0), ('Medium', 1), ('Hard', 2)], default=0),
        ),
    ]
