# Generated by Django 2.2.4 on 2022-01-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20220118_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')], default=0),
        ),
    ]
