# Generated by Django 2.2.4 on 2022-01-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
