# Generated by Django 2.2.4 on 2022-01-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_player_total_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='solved_questions',
            field=models.ManyToManyField(blank=True, related_name='solved_by', to='backend.Question'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='tc_id',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
