# Generated by Django 2.2.4 on 2022-01-18 07:30

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_testcase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description_rendered',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=markdownfield.models.MarkdownField(rendered_field='description_rendered', use_editor=False),
        ),
    ]
