# Generated by Django 2.2.4 on 2022-01-26 08:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20220119_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='description_rendered',
        ),
        migrations.AddField(
            model_name='question',
            name='solution_template',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
