# Generated by Django 2.2.4 on 2022-01-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20220126_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='solution_template',
        ),
        migrations.CreateModel(
            name='SkillSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('questions', models.ManyToManyField(related_name='skill_sets', to='backend.Question')),
            ],
        ),
    ]
