# Generated by Django 2.2.4 on 2022-01-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20220126_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillset',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='skill_sets', to='backend.Question'),
        ),
    ]
