# Generated by Django 2.2.4 on 2022-01-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20220126_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='Question', max_length=50),
            preserve_default=False,
        ),
    ]
