# Generated by Django 2.2.4 on 2022-01-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_question_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='total_points',
            new_name='total_score',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='points',
            new_name='score',
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=False)),
                ('questions', models.ManyToManyField(blank=True, related_name='modules', to='backend.Question')),
            ],
        ),
    ]
