# Generated by Django 2.2.4 on 2022-01-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20220128_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
