# Generated by Django 2.2.4 on 2022-01-28 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_question_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillset',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='skillset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='backend.SkillSet'),
            preserve_default=False,
        ),
    ]
