# Generated by Django 2.2.4 on 2022-02-07 04:38

from django.db import migrations, models
import django.utils.timezone
from random import randint

def rand():
	return randint(1, 10000)

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20220128_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default=rand, unique=False),
            preserve_default=False,
        ),
    ]
