# Generated by Django 2.2.4 on 2022-02-07 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_auto_20220207_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='compile',
            name='question',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='compile_logs', to='backend.Question'),
            preserve_default=False,
        ),
    ]
