# Generated by Django 2.2.4 on 2022-02-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_auto_20220208_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Wrong Answer'), (1, 'Compilation Error'), (2, 'Accepted')], default=None, null=True, verbose_name='Status'),
        ),
    ]
