# Generated by Django 2.2.4 on 2022-02-09 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_auto_20220208_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Player'),
            preserve_default=False,
        ),
    ]
