# Generated by Django 2.2.4 on 2022-02-09 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_submission_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='compile_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.Compile'),
        ),
    ]
