# Generated by Django 2.2.4 on 2022-02-09 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_auto_20220209_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='compile_log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='backend.Compile'),
        ),
    ]
