# Generated by Django 2.2.4 on 2022-02-11 07:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_auto_20220209_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solution_template',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
