# Generated by Django 2.2.4 on 2022-02-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_question_solution_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='solution_template',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
