# Generated by Django 2.2.4 on 2022-02-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_auto_20220211_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillset',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
