# Generated by Django 2.2.4 on 2022-02-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_skillset_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillset',
            old_name='name',
            new_name='title',
        ),
    ]
