# Generated by Django 2.2.4 on 2022-02-15 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_auto_20220214_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='name',
            new_name='title',
        ),
    ]
