# Generated by Django 2.2.4 on 2022-02-16 03:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_auto_20220216_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='compile',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='idss',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.UUIDField(default=uuid.UUID('74fd1099-57c8-4c03-8047-c860a38fb428'), primary_key=True, serialize=False),
        ),
    ]
