# Generated by Django 2.2.4 on 2022-02-16 03:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_auto_20220216_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='submission',
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bf5bb138-544a-4774-8c50-3a9cb48586fe'), primary_key=True, serialize=False),
        ),
    ]
