# Generated by Django 2.2.4 on 2022-02-16 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_testresult_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='idss',
            new_name='uid',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='submission',
        ),
    ]
