# Generated by Django 2.2.4 on 2022-02-16 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_testresult_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compile',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
