# Generated by Django 2.2.4 on 2022-02-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_auto_20220216_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='compile',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
