# Generated by Django 2.2.4 on 2022-02-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_auto_20220216_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='compile_log',
        ),
    ]
