# Generated by Django 2.2.4 on 2022-02-18 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_submission_compile_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='testcase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to='backend.TestCase'),
        ),
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together={('testcase', 'submission')},
        ),
    ]
