# Generated by Django 2.2.4 on 2022-02-21 03:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_auto_20220218_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
