# Generated by Django 2.2.4 on 2022-02-21 03:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_testresult_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='id',
        ),
        migrations.AlterField(
            model_name='testresult',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
