# Generated by Django 2.2.4 on 2022-02-21 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0061_auto_20220221_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='backend.TestCase'),
        ),
    ]
